### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': '[data-path='~/elixir_proje...

### ISSUE THREAD

**Issue by hugohernani** [DavidLGoldberg/jumpy#121]
[Enter steps to reproduce:]

1. ... Hit shift + enter to see the generated pair of letters
2. ... errors out due to an open pane/tab with elixir code.

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Pop!_OS 20.04
**Thrown From**: [jumpy](https://github.com/DavidLGoldberg/jumpy) package 5.0.2

### Stack Trace

Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': '[data-path='/home/hugohernani/elixir_projects/learning_it/programming book - Exercises (Dave's book Pragprog)/spawn/spawn1.exs']' is not a valid selector.

```
At /home/hugohernani/.atom/packages/jumpy/dist/labelers/tabs.js:15

Error: Failed to execute 'querySelector' on 'Element': '[data-path='/home/hugohernani/elixir_projects/learning_it/programming book - Exercises (Dave's book Pragprog)/spawn/spawn1.exs']' is not a valid selector.
    at TabLabel.drawLabel (/packages/jumpy/dist/labelers/tabs.js:15:14)
    at JumpyView.loadLabels (/packages/jumpy/dist/jumpy-view.js:131:41)
    at JumpyView.toggle (/packages/jumpy/dist/jumpy-view.js:140:18)
    at /packages/jumpy/dist/jumpy-view.js:68:42)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:350265)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1230852)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1226986)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:284919)
```

### Commands

```
     -1:48.9.0 pane:show-next-item (input.hidden-input)
     -1:48.5.0 core:save (input.hidden-input)
     -1:47.6.0 jumpy:toggle (input.hidden-input)
     -1:36 intentions:highlight (input.hidden-input)
     -1:35.1.0 core:undo (input.hidden-input)
     -1:34 jumpy:reset (input.hidden-input)
     -1:33.1.0 jumpy:clear (input.hidden-input)
     -1:32.3.0 intentions:highlight (input.hidden-input)
     -1:31.1.0 core:save (input.hidden-input)
     -1:29.9.0 intentions:highlight (input.hidden-input)
     -1:29.7.0 pane:show-previous-item (input.hidden-input)
     -1:29.2.0 pane:show-next-item (input.hidden-input)
  2x -1:24.5.0 intentions:highlight (input.hidden-input)
     -1:23.5.0 settings-view:open (input.hidden-input)
     -0:02.6.0 core:close (a.)
     -0:01.5.0 jumpy:toggle (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-ruby 1.7.0 
aligner-typescript 1.0.0 
atom-beautify 0.33.4 
atom-blue-jeans-ui 0.5.0 
atom-clock 0.1.18 
atom-elixir-formatter 2.0.0 
atom-ide-ui 0.13.0 
atom-inline-blame 0.0.10 
atom-pug 0.2.0 
atom-react 0.4.0 
atom-ternjs 0.20.0 
atom-toolbar 0.1.6 
atom-typescript 14.1.2 
bread-syntax 0.2.0 
bread-ui 0.3.0 
busy-signal 2.0.1 
case-keep-replace 0.6.2 
color-picker 2.3.0 
cream-soda-ui 0.2.2 
dart 1.0.1 
docblockr 0.13.7 
dockerletion 0.2.0 
editorconfig 2.6.1 
emmet 2.4.3 
expressjs 2.2.0 
file-icons 2.1.44 
git-blame 1.8.0 
git-diff-plus 0.4.2 
goto-definition 1.3.4 
hacker-dream-syntax 1.4.8 
hacker-dream-ui 1.1.0 
hey-pane 1.2.0 
highlight-selected 0.17.0 
hyperclick 0.1.5 
ide-elixir 0.2.25 
inline-git-diff 2.4.0 
intentions 1.1.5 
javascript-refactor 0.7.1 
jumpy 5.0.2 
jumpy-beacon 0.2.0 
language-babel 2.85.0 
language-docker 1.1.8 
language-ejs 0.4.0 
language-elixir 0.24.0 
language-protobuf 0.7.1 
language-typescript-react 0.1.1 
linter 3.3.0 
linter-elixir-credo 1.1.0 
linter-erb 1.1.5 
linter-eslint 8.5.5 
linter-pug 2.0.14 
linter-rubocop 2.5.7 
linter-ruby 1.3.1 
linter-ui-default 3.2.4 
modern-javascript-snippets 1.1.0 
pigments 0.40.6 
prettier-atom 0.60.1 
project-folder 1.5.0 
project-manager 3.3.8 
react-es7-snippets 0.5.0 
reactstrap-snippets 0.5.2 
related 0.3.5 
sync-settings 5.0.9 
tab-foldername-index 3.3.2 
teletype 0.13.4 
toggle-quotes 1.1.4 
```

**Comment by hugohernani** [comment]
It seems like the problem is with folder's name: `/programming book - Exercises (Dave's book Pragprog)`. The query selector used does not seem to consider some characters in folder's name.

**Comment by DavidLGoldberg** [comment]
heh, yeah figured that was it.  I'll look at this tonight and see if there is anything I can do.. Never saw something like this actually :) ....Also my VS Code version is coming soon (fingers crossed)
