### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by mangledmonkey** [DavidLGoldberg/jumpy#45]
[Enter steps to reproduce below:]

1. shift-enter shortcut

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10.1
**Thrown From**: [jumpy](https://github.com/DavidLGoldberg/jumpy) package, v2.0.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/brandon/.atom/packages/jumpy/lib/jumpy-view.coffee:112

TypeError: undefined is not a function
  at /Users/brandon/.atom/packages/jumpy/lib/jumpy-view.coffee:112:28
  at Array.filter (native)
  at JumpyView.module.exports.JumpyView.turnOffSlowKeys (/Users/brandon/.atom/packages/jumpy/lib/jumpy-view.coffee:111:59)
  at JumpyView.module.exports.JumpyView.toggle (/Users/brandon/.atom/packages/jumpy/lib/jumpy-view.coffee:122:10)
  at atom-workspace.atom.commands.add.jumpy:toggle (/Users/brandon/.atom/packages/jumpy/lib/jumpy-view.coffee:39:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
     -0:00.0 jumpy:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "tabs",
      "enhanced-package-list",
      "atom-color-highlight",
      "log-console",
      "open-in-github-app",
      "tree-view",
      "project-colorize"
    ],
    "themes": [
      "newton-dark-ui",
      "peacock-syntax"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
achievements, v0.6.1
auto-update-packages, v0.2.2
autocomplete-plus, v1.1.0
envygeeks-file-icons, v0.2.1
file-type-icons, v0.5.3
go-plus, v3.0.13
highlight-selected, v0.7.0
language-less, v0.24.0
language-nginx, v0.4.0
linter, v0.9.1
minimap, v3.5.4
minimap-git-diff, v3.1.0
minimap-highlight-selected, v3.1.0
newton-dark-ui, v1.0.3
peacock-syntax, v1.2.2
save-session, v0.11.3
script, v2.16.0
sublime-tabs, v0.4.8
symbols-tree-view, v0.3.2
vim-mode, v0.26.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by DavidLGoldberg** [comment]
Do you have shadow enabled?

**Comment by DavidLGoldberg** [comment]
I've been using Jumpy on newest 2.0.1 with 0.169.0 for work related projects.

I don't see this on my end yet.  Do you have any more insight by any chance?

**Comment by DavidLGoldberg** [comment]
I am on Mac OSX 10.9.4... Doubt it though :\

**Comment by mangledmonkey** [comment]
I have toggled DOM shadow, and have disabled all other non-core plugins, on Mac Yosemite 10.10.1 in Atom 0.169.0.

Jumpy was working fine after the initial installation. Then I'd messed around with other plugins and Atom automatically updated 0.169.0 (I'm not sure what I had before, but it was previously updated within the past couple days).

I have disabled all other plugins (reloading the interface, restarting Atom..), but the error persists.

**Comment by mangledmonkey** [comment]
hmmm... I had also modified the keymap file for some custom navigation. After commenting out my changes then enabling them line by line and reloading the interface, Jumpy is working once more.

This was the problem.

'editor':
    'normalizeIndentOnPaste': false

I forget why I had that in there, since I think this can be set in the Settings now. But removing that restored Jumpy's functionality.

Thanks for your quick responses!  :D

**Comment by DavidLGoldberg** [comment]
Do you think I should reopen this as a low priority bug?

Is it easily reproducible by just enabling that setting? I'll reopen for the moment, and close it after I give it a quick test!

Thanks so much for clarifying!
-David

**Comment by mangledmonkey** [comment]
For me it could be reproduced. After uncommenting all other options in the
config, toggling that single setting would also toggle the error.




On Friday, January 9, 2015, David L. Goldberg <notifications@github.com>
wrote:

> Do you think I should reopen this as a low priority bug?
>
> Is it easily reproducible by just enabling that setting? I'll reopen for
> the moment, and close it after I give it a quick test!
>
> Thanks so much for clarifying!
> -David
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DavidLGoldberg/jumpy/issues/45#issuecomment-69432773>.
>


-- 

-- Brandon West




www.mangledmonkeymedia.com

**Comment by DavidLGoldberg** [comment]
Ok, I'll take a look at it!

Thanks again!

**Comment by DavidLGoldberg** [comment]
I can reproduce it after an atom reload.  New stack trace is:

```
TypeError: undefined is not a function
  at /Users/dgoldberg/github/jumpy/lib/jumpy-view.coffee:127:28
  at Array.filter (native)
  at JumpyView.module.exports.JumpyView.getFilteredJumpyKeys (/Users/dgoldberg/github/jumpy/lib/jumpy-view.coffee:126:33)
  at JumpyView.module.exports.JumpyView.initKeyFilters (/Users/dgoldberg/github/jumpy/lib/jumpy-view.coffee:120:31)
  at JumpyView.module.exports.JumpyView.initialize (/Users/dgoldberg/github/jumpy/lib/jumpy-view.coffee:64:10)
  at JumpyView.View (/Users/dgoldberg/github/jumpy/node_modules/space-pen/lib/space-pen.js:178:25)
  at new JumpyView (/Users/dgoldberg/github/jumpy/lib/jumpy-view.coffee:36:5)
  at Object.module.exports.activate (/Users/dgoldberg/github/jumpy/lib/jumpy.coffee:26:26)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:741:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:223:20)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)
```

**Comment by DavidLGoldberg** [comment]
Thanks for this.  I'll play with it for a day and then push a patch version.
