### ISSUE TITLE
Failed to activate the jumpy package

### ISSUE THREAD

**Issue by basarat** [DavidLGoldberg/jumpy#59]
Suspect this is with latest atom update `.206`

1. Opened a markdown file
2. Pressed `shift+enter`

**Atom Version**: 0.206.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [jumpy](https://github.com/DavidLGoldberg/jumpy) package, v2.0.6

### Stack Trace

Failed to activate the jumpy package

```
At Cannot read property 'keyBindings' of undefined

TypeError: Cannot read property 'keyBindings' of undefined
  at JumpyView.module.exports.JumpyView.initialize (C:\Users\basaratsyed\.atom\packages\jumpy\lib\jumpy-view.coffee:55:51)
  at JumpyView.View (C:\Users\basaratsyed\.atom\packages\jumpy\node_modules\space-pen\lib\space-pen.js:178:25)
  at new JumpyView (C:\Users\basaratsyed\.atom\packages\jumpy\lib\jumpy-view.coffee:36:5)
  at Object.module.exports.activate (C:\Users\basaratsyed\.atom\packages\jumpy\lib\jumpy.coffee:26:26)
  at Package.module.exports.Package.activateNow (C:\Users\basaratsyed\AppData\Local\atom\app-0.206.0\resources\app.asar\src\package.js:238:19)
  at C:\Users\basaratsyed\AppData\Local\atom\app-0.206.0\resources\app.asar\src\package.js:770:25
  at Emitter.module.exports.Emitter.emit (C:\Users\basaratsyed\AppData\Local\atom\app-0.206.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\basaratsyed\AppData\Local\atom\app-0.206.0\resources\app.asar\src\command-registry.js:219:20)
  at C:\Users\basaratsyed\AppData\Local\atom\app-0.206.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\basaratsyed\AppData\Local\atom\app-0.206.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\basaratsyed\AppData\Local\atom\app-0.206.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\basaratsyed\AppData\Local\atom\app-0.206.0\resources\app.asar\src\window-event-handler.js:177:20)

```

### Commands

```
     -0:03.2.0 jumpy:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "ignoredNames": [
      ".git",
      ".tscache",
      ".scssc"
    ],
    "disabledPackages": [
      "whitespace",
      "atom-ternjs",
      "minimap"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.9
atom-pair, v1.1.6
atom-typescript, v4.5.6
autocomplete-emojis, v2.2.2
css-snippets, v0.8.0
docblockr, v0.7.2
jumpy, v2.0.6
language-fsharp, v0.8.4
last-cursor-position, v0.9.0
linter, v0.12.6
linter-htmlhint, v0.0.16
linter-jsonlint, v0.1.4
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
monokai, v0.14.0
pain-split, v1.4.0
project-manager, v1.15.8
react, v0.12.0
save-session, vundefined
symbols-tree-view, v0.9.3
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by basarat** [comment]
🌹

**Comment by DavidLGoldberg** [comment]
:-)

**Comment by DavidLGoldberg** [comment]
I'm going to start using that --one option to see if it's compatible with 1.0.  I had suggested a Canary like think a while back, kind of like that, didn't know they made it...  Not sure I would have caught it because the PR that broke it was very recent anyway heh

**Comment by weijarz** [comment]
It still throws this exception on version 1.10.2 (Arch Linux)
