### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by cperryk** [DavidLGoldberg/jumpy#63]
Getting this error after Atom upgrade to 0.207. It happens whenever I try to jump.

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.4
**Thrown From**: [jumpy](https://github.com/DavidLGoldberg/jumpy) package, v2.0.9

### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of null

```
At /Users/kirkcp/.atom/packages/jumpy/lib/jumpy-view.coffee:164

TypeError: Cannot read property 'querySelector' of null
  at /Users/kirkcp/.atom/packages/jumpy/lib/jumpy-view.coffee:164:46
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:267:9)
  at JumpyView.module.exports.JumpyView.toggle (/Users/kirkcp/.atom/packages/jumpy/lib/jumpy-view.coffee:158:41)
  at atom-workspace.commands.add.atom.commands.add.jumpy:toggle (/Users/kirkcp/.atom/packages/jumpy/lib/jumpy-view.coffee:44:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
  8x -0:06.2.0 core:backspace (input.hidden-input)
     -0:05.1.0 jumpy:toggle (input.hidden-input)
  2x -0:04.0 core:backspace (input.hidden-input)
     -0:03.5.0 editor:consolidate-selections (input.hidden-input)
     -0:03.5.0 core:cancel (input.hidden-input)
     -0:02.3.0 jumpy:toggle (input.hidden-input)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".DS_Store",
      ".sass-cache",
      ".ftppass",
      "*.sublime-project",
      "*.sublime-workspace"
    ],
    "disabledPackages": [
      "htmlhint",
      "sublime-tabs",
      "atom-lint",
      "spell-check",
      "atom-deconsole",
      "atom-jshint",
      "javascript-snippets",
      "color",
      "filetype-color",
      "docblockr",
      "autoclose-html",
      "file-type-icons",
      "language-javascript-semantic",
      "linter-coffeelint",
      "build",
      "coffee-compile",
      "tabs-to-spaces",
      "incompatible-packages",
      "deprecation-cop",
      "save-commands"
    ],
    "themes": [
      "atom-ice-cold-ui",
      "ice-cold-syntax-modified"
    ]
  },
  "jumpy": {
    "highContrast": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ice-cold-ui, v0.3.0
atom-jsx-transform, v0.2.0
color-picker, v2.0.4
file-icons, v1.5.7
highlight-selected, v0.9.3
ice-cold-syntax-modified, v0.1.0
jumpy, v2.0.9
language-ejs, v0.1.0
language-jade, v0.4.0
linter, v0.12.6
linter-jshint, v0.1.6
linter-php, v0.0.15
linter-scss-lint, v1.0.4
pain-split, v1.4.0
pretty-json, v0.3.3
project-manager, v1.15.10
react, v0.12.0
sass-autocompile, v0.7.0
tab-numbers, v0.2.0
terminal-panel, v1.14.1
webbox-color, v0.5.7

# Dev
No dev packages
```

**Comment by cperryk** [comment]
I'm also noticing that after this error occurs I cannot use the backspace or escape keys when using the command palette.

**Comment by DavidLGoldberg** [comment]
I'm on OS X 10.9.4 otherwise same versions.

Can you do me a favor and hit control + alt + command + l (lower case L) to reload atom...

Also, if that doesn't work, try
`apm install jumpy` or `apm upgrade jumpy` (whichever of those works)

Stuff broke bad with Atom 0.206.0, but starting from 2.0.7 Jumpy and on it was working with me for 0.207.0 (weird coincidence in versions)

Thanks for the feedback.  Any help in clarifying will be greatly appreciated!

**Comment by DavidLGoldberg** [comment]
Btw, there was something broken related to keymaps as well  (Few things were broken).  I have a feeling you don't have the latest jumpy loaded (somehow, not sure)

**Comment by DavidLGoldberg** [comment]
Also, just so we're clear, you're not on dev mode Atom right?

**Comment by DavidLGoldberg** [comment]
Oh, one more thing, do you have shadow dom selected in the main settings page.  I'm only supporting that.  It's been the default for a long time now and everyone else seems to be on board.

**Comment by cperryk** [comment]
Ah, I enabled shadow dom and everything is working as expected now. Thank you!

**Comment by DavidLGoldberg** [comment]
:+1:
