### ISSUE TITLE
Failed to activate the jumpy package

### ISSUE THREAD

**Issue by weijarz** [DavidLGoldberg/jumpy#94]
[Enter steps to reproduce below:]

1. Pressed `shift+enter`

**Atom Version**: 1.10.2
**Electron Version**: 1.4.2
**System**: linux 4.4.23-1-lts
**Thrown From**: [jumpy](https://github.com/DavidLGoldberg/jumpy) package, v3.1.2

### Stack Trace

Failed to activate the jumpy package

```
At Object.observe is not a function

TypeError: Object.observe is not a function
    at JumpyView.initKeyFilters (/home/wjzhou/.atom/packages/jumpy/lib/jumpy-view.coffee:118:16)
    at JumpyView.initialize (/home/wjzhou/.atom/packages/jumpy/lib/jumpy-view.coffee:61:10)
    at JumpyView.View [as constructor] (/home/wjzhou/.atom/packages/jumpy/node_modules/space-pen/lib/space-pen.js:178:25)
    at new JumpyView (/home/wjzhou/.atom/packages/jumpy/lib/jumpy-view.coffee:32:5)
    at Object.activate (/home/wjzhou/.atom/packages/jumpy/lib/jumpy.coffee:29:26)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:183:20)
    at /usr/lib/atom/src/package.js:798:25
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:241:20)
    at /usr/lib/atom/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/lib/atom/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:00.1.0 jumpy:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "automaticallyUpdate": false,
    "disabledPackages": [
      "spell-check",
      "background-tips"
    ],
    "packagesWithKeymapsDisabled": [
      "ctrl-dir-scroll",
      "autocomplete-plus",
      "fuzzy-finder",
      "git-history",
      "sort-lines",
      "tab-switcher",
      "git-diff-details"
    ],
    "projectHome": "/home/wjzhou/ws"
  },
  "jumpy": {
    "fontSize": 0.7
  }
}
```

### Installed Packages

```coffee
# User
atom-terminal, v0.8.0 (inactive)
color-picker, v2.2.2 (active)
ctrl-dir-scroll, v0.2.2 (inactive)
dark-pastel-eighties-syntax, v0.4.0 (inactive)
editorconfig, v1.4.1 (active)
git-history, v3.2.0 (inactive)
goto-definition, v1.1.19 (active)
highlight-selected, v0.11.2 (active)
indentation-indicator, v1.0.0 (active)
jumpy, v3.1.2 (inactive)
language-ini, v1.16.0 (active)
last-cursor-position, v0.9.0 (active)
open-recent, v5.0.0 (active)
sort-lines, v0.14.0 (inactive)
zen-black-syntax, v0.0.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (inactive)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by DavidLGoldberg** [comment]
Yuck.  I knew this would happen, I was trying to figure out a clean solution.  I'll have to make a patch tonight.

:-(

I added Travis, and it's supposed to build the unstable branches...

1. I thought travis was constantly building (oops it's not)
2. I built 6 days ago and it was fine in both branches... why don't they wait before upgrading stable?  They updated Chrome to the new one without Object.observe() :(

I'll patch it tonight if no one provides a passing PR before then.

**Comment by DavidLGoldberg** [comment]
!

I actually can't reproduce this on my mac!  (Latest versions of Atom of course)

Are you on some beta branch?

**Comment by DavidLGoldberg** [comment]
btw, relates to:
https://discuss.atom.io/t/api-observe-key-binding-changes/32921

I can probably just remove those 2 lines, they were there to be safe.  But regardless can't yet reproduce the issue.

**Comment by DavidLGoldberg** [comment]
Can't reproduce on a windows machine either.

**Comment by DavidLGoldberg** [comment]
Shamefully, I don't have access to a linux box at the moment, I have a branch for this I can push at any point but I'd like confirmation that it's linux that's the issue.

**Comment by weijarz** [comment]
I noticed that Arch Linux's Atom package uses a newer electron version (1.4.3) than Atom official version (1.3.6).

<https://www.archlinux.org/packages/community/x86_64/atom/>
<https://www.archlinux.org/packages/community/x86_64/electron/>

**Comment by DavidLGoldberg** [comment]
Thanks so much.  I have a quick dirty fix I could release, but I think it might cause some issues, I have an idea of how to do this a bit differently.  I'll try to get a release out tonight.

**Comment by DavidLGoldberg** [comment]
btw: https://discuss.atom.io/t/object-observe/34532

**Comment by DavidLGoldberg** [comment]
Lee Dohm brings up that the build you're on is not supported.

**Comment by DavidLGoldberg** [comment]
That said this was on my list to fix for a while.  @johngeorgewright Mind taking a quick peek at this and signing off?   I'll have another friend give it a peek too.

**Comment by DavidLGoldberg** [comment]
Also, I set up daily builds with travis ci for jumpy + qolor now.  Should help, if and when the beta branch breaks.

**Comment by johngeorgewright** [comment]
Soz... on London time, just saw this. Pull request looks good.
